service:
  name: weekly-menu-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  # memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  environment:
    DISHES_TABLE_NAME: ${self:custom.DishesTable.name}
    MENUS_TABLE_NAME: ${self:custom.MenusTable.name}
  iamRoleStatements:
    - ${file(iam/DishesTableIAM.yml):DishesTableIAM}
    - ${file(iam/MenusTableIAM.yml):MenusTableIAM}

resources:
  Resources:
    DishesTable: ${file(resources/DishesTable.yml):DishesTable}
    MenusTable: ${file(resources/MenusTable.yml):MenusTable}

functions:
  createDish:
    handler: src/handlers/createDish.handler
    events:
      - http:
          method: POST
          path: /dishes
          cors: true
          # authorizer: ${self:custom.authorizer}

  getDishes:
    handler: src/handlers/getDishes.handler
    events:
      - http:
          method: GET
          path: /dishes
          cors: true
          # authorizer: ${self:custom.authorizer}

  getDish:
    handler: src/handlers/getDish.handler
    events:
      - http:
          method: GET
          path: /dishes/{id}
          cors: true
          # authorizer: ${self:custom.authorizer}

  deleteDish:
    handler: src/handlers/deleteDish.handler
    events:
      - http:
          method: DELETE
          path: /dishes/{id}
          cors: true
          # authorizer: ${self:custom.authorizer}

  createMenu:
    handler: src/handlers/createMenu.handler
    events:
      - http:
          method: POST
          path: /menus
          cors: true
          # authorizer: ${self:custom.authorizer}

  getMenus:
    handler: src/handlers/getMenus.handler
    events:
      - http:
          method: GET
          path: /menus
          cors: true

  getMenu:
    handler: src/handlers/getMenu.handler
    events:
      - http:
          method: GET
          path: /menus/{menuId}
          cors: true

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:weekly-menu-auth-service-${self:provider.stage}-auth
  DishesTable:
    name: !Ref DishesTable
    arn: !GetAtt DishesTable.Arn
  MenusTable:
    name: !Ref MenusTable
    arn: !GetAtt MenusTable.Arn
