service:
  name: weekly-menu-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  # memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  environment:
    DISHES_TABLE_NAME: ${self:custom.DishesTable.name}
  iamRoleStatements:
    - ${file(iam/DishesTableIAM.yml):DishesTableIAM}

resources:
  Resources:
    DishesTable: ${file(resources/DishesTable.yml):DishesTable}

functions:
  createDish:
    handler: src/handlers/createDish.handler
    events:
      - http:
          method: POST
          path: /dishes

  getDishes:
    handler: src/handlers/getDishes.handler
    events:
      - http:
          method: GET
          path: /dishes

  getDish:
    handler: src/handlers/getDish.handler
    events:
      - http:
          method: GET
          path: /dishes/{id}/{name}

custom:
  DishesTable:
    name: !Ref DishesTable
    arn: !GetAtt DishesTable.Arn
