service:
  name: weekly-menu-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  # memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

functions:
  createDish:
    handler: src/handlers/createDish.handler
    events:
      - http:
          method: POST
          path: /dishes
