MenusTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: MenusTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: startDate
        AttributeType: S
      - AttributeName: menuId
        AttributeType: S

    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: startDate
        KeyType: RANGE

    GlobalSecondaryIndexes:
      - IndexName: menuIdGlobalIndex
        KeySchema:
          - AttributeName: menuId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
